#!/usr/bin/env bash
#setup a 404 page

link="https://www.youtube.com/watch?v=6Qpju4uY-v4"
new_conf="server_name _;\n\trewrite ^/redirect_me/$ $link permanent;"
location_error="location = /404.html {\n\t\troot /var/www/html/;\n\t\tinternal;\n"
error_directive="error_page 404 /404.html;\n\t$location_error"
error_404="}\n\n\t$error_directive\t}"

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World" | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" > sudo tee /var/www/html/404.html
sudo sed -i "s|server_name\ _;|$new_conf|" /etc/nginx/sites-available/default
sudo sed -i "0,/}/ s|}|$error_404|" /etc/nginx/sites-available/default
sudo service nginx restart
