#!/usr/bin/env bash
#holberton 10 times but 9th time says hi
i="0"

while [ $i -le 9 ]
	       do
	if
		[ $i == 9 ]
	then
		echo "Hi"
	fi
		       echo "Holberton School"
		       (( i++ ))
	
	       done
