#!/usr/bin/env bash
#1-20 but 4 9 and 17 are unlcuky
i=1
while [ $i -le 20 ] 
	do
		echo $i
		((i++))
		case $i in 
		5)
			echo "bad luck from China"
			;;
		10)
			echo "bad luck from Japan"
			;;
		18)
			echo "bad luck from Italy"
			;;
	esac
done
