#!/usr/bin/env bash
#holberton school file if else empty not empty

if [ -e holbertonschool ]
	then
		echo "holbertonschool file exists"
	if [ -s holbertonschool ]
		then 
			echo "holbertonschool file is not empty"
		else 
			echo "holbertonschool is empty"
	fi
	if [ -f holbertonschool ]
		then 
			echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
