#!/usr/bin/env bash
# setting up HAproxy:
sudo apt-get -y update
sudo apt-get -y install haproxy

string="\nfrontend myfrontend
\n\tbind *:80
\n\tstats uri /haproxy?stats
\n\tdefault_backend myservers
\n\nbackend myservers
\n\tbalance roundrobin
\n\tserver 3599-web-01 3.90.188.172:80 check
\n\tserver 3599-web-02 54.243.24.124:80 check"

sudo echo -e "$string" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
