#!/usr/bin/env bash
# setting up HAproxy:
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
start="frontend http_web
\n\tbind *:80
\n\tstats uri /haproxy?stats
\n\tdefault_backend custom_backend
\n\backend custom_backend
\n\tbalance roundrobin
\n\tserver web-01 52.90.144.186:80 check
\n\tserver web-02 100.26.51.3:80 check"
echo -e "$start" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo service haproxy restart
